name: Tests

on: ['push', 'pull_request']

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.3, 8.4, 8.5]

        name: PHP ${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip
                  coverage: pvoc

            - name: Install dependencies
              run: composer install --prefer-dist --no-interaction --no-progress

            - name: Run tests
              run: composer test
